spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      show-sql: true
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
